[project]
name = "cve-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp[speedups]>=3.11.18",
    "feedparser>=6.0.11",
    "nltk>=3.9.1",
]
